#!/usr/bin/env python3
# Embed a binary as a C++ header: const unsigned char array + size.
import sys, os

def main(bin_path, out_path, name):
    data = open(bin_path, 'rb').read()
    with open(out_path, 'w') as f:
        f.write(f"// Auto-generated by embed.py — do not edit.\n")
        f.write(f"#pragma once\n")
        f.write(f"static const unsigned char {name}[] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write(f"}};\n")
        f.write(f"static const unsigned int {name}_len = {len(data)}u;\n")
    print(f"embedded {len(data)} bytes -> {out_path}")

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
